base:
  image: 10.100.198.200:5000/migs-base
  ports:
    - 8080
  environment:
    - SERVICE_NAME=migs-base

app:
  extends:
    service: base
  links:
    - db:db

app-blue:
  extends:
    service: base
  environment:
    - SERVICE_NAME=migs-base-blue
  links:
    - db:db

app-green:
  extends:
    service: base
  environment:
    - SERVICE_NAME=migs-base-green
  links:
    - db:db

applocal:
  extends:
    service: base
  links:
    - db:db

db:
  image: mongo
