app:
  image: migspulido/migs-base
  ports:
    - 8080
  environment:
    - SERVICE_NAME=migs-base
    - DB_HOST=books-ms-db

app-blue:
  environment:
    - SERVICE_NAME=migs-base-blue
  extends:
    service: app

app-green:
  environment:
    - SERVICE_NAME=migs-base-green
  extends:
    service: app

db:
  container_name: migs-base-db
  image: mongo
  environment:
    - SERVICE_NAME=migs-base-db

integ:
  image: migspulido/migs-base-tests
  volumes:
    - ./src:/source/src
  environment:
    - TEST_TYPE=integ
    - DOMAIN=$DOMAIN